#!/usr/bin/env python3
"""
Module async_comprehension demonstrates the usage of asynchronous
comprehension to collect values from an asynchronous generator,
specifically collecting random numbers generated by async_generator.
"""

from typing import List
# Assuming async_generator is in the same directory. Adjust import as necessary.
from async_generator import async_generator

async def async_comprehension() -> List[float]:
    """
    Asynchronously collects random numbers generated by async_generator
    using asynchronous comprehension.

    Returns:
        List[float]: A list of collected random numbers.
    """
    return [i async for i in async_generator()]

